// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6hB2fBMKhtC_UoZmsPCx3BmbBd2XnnE',
    appId: '1:577076615632:android:f924dfc56c168ca20981d5',
    messagingSenderId: '577076615632',
    projectId: 'gt-face-notify',
    databaseURL: 'https://gt-face-notify.firebaseio.com',
    storageBucket: 'gt-face-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUqiTmuxZfCj1yGVqyoCDbINUogM6k8A',
    appId: '1:577076615632:ios:ba0aa0ab18298ae30981d5',
    messagingSenderId: '577076615632',
    projectId: 'gt-face-notify',
    databaseURL: 'https://gt-face-notify.firebaseio.com',
    storageBucket: 'gt-face-notify.appspot.com',
    androidClientId: '577076615632-etupudnc6rjb1j60ap6r2mq5qg1mvttk.apps.googleusercontent.com',
    iosBundleId: 'vn.com.goldtek.flutterApp',
  );

}